# Generated by Django 4.1.1 on 2022-09-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinventory', '0002_pcs_monitor1_pcs_monitor2'),
    ]

    operations = [
        migrations.AddField(
            model_name='platz',
            name='maus',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='platz',
            name='tastator',
            field=models.BooleanField(default=None),
        ),
    ]
