# Generated by Django 4.1.1 on 2022-09-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinventory', '0003_platz_maus_platz_tastator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platz',
            name='maus',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='platz',
            name='tastator',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
