# Generated by Django 4.1.1 on 2022-09-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinventory', '0004_alter_platz_maus_alter_platz_tastator'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='bemaerkung',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='pcs',
            name='bemaerkung',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
