# Generated by Django 4.1.1 on 2022-10-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinventory', '0007_monitor_status_pcs_status_alter_monitor_bemaerkung_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcs',
            name='pc',
        ),
        migrations.AlterField(
            model_name='platz',
            name='pc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itinventory.pcs'),
        ),
    ]
