# Generated by Django 4.1.1 on 2022-10-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinventory', '0008_remove_pcs_pc_alter_platz_pc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platz',
            old_name='tastator',
            new_name='tastatur',
        ),
    ]
