# Generated by Django 4.1.1 on 2022-10-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinventory', '0009_rename_tastator_platz_tastatur'),
    ]

    operations = [
        migrations.AddField(
            model_name='platz',
            name='bemaerkung',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
