# Generated by Django 4.1.1 on 2022-12-14 12:46

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinventory', '0010_platz_bemaerkung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platz',
            name='maus',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='platz',
            name='monitor1',
            field=models.ForeignKey(default=33, on_delete=builtins.callable, related_name='Monitor1', to='itinventory.monitor'),
        ),
        migrations.AlterField(
            model_name='platz',
            name='monitor2',
            field=models.ForeignKey(default=33, on_delete=builtins.callable, related_name='Monitor2', to='itinventory.monitor'),
        ),
        migrations.AlterField(
            model_name='platz',
            name='pc',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='itinventory.pcs'),
        ),
        migrations.AlterField(
            model_name='platz',
            name='tastatur',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
