# Generated by Django 4.1.4 on 2022-12-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinventory', '0013_alter_platz_maus_alter_platz_tastatur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platz',
            name='pc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='itinventory.pcs'),
        ),
    ]
