# Generated by Django 4.1.4 on 2023-01-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinventory', '0015_alter_platz_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platz',
            name='monitor1',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Monitor1', to='itinventory.monitor'),
        ),
        migrations.AlterField(
            model_name='platz',
            name='monitor2',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Monitor2', to='itinventory.monitor'),
        ),
    ]
